# Generated by Django 5.2.8 on 2025-11-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=30)),
                ('year', models.DateField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
